import java.io.File
import java.nio.file.Files
import java.security.MessageDigest

group 'com.alexmercerind.media_kit_libs_android_video'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.alexmercerind.media_kit_libs_android_video'
    }

    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
    }

    dependencies {
        implementation fileTree(dir: "$buildDir/output", include: "*.jar")
    }
}

task downloadDependencies(type: Exec) {   
        // Delete previously created /output subdirectory.

        def outputDir = file("$buildDir/output")
        if (outputDir.exists()) {
            outputDir.deleteDir()
        }
        outputDir.mkdirs()

        // Download all *.jar dependencies & verify their SHA-256 checksums.
        def filesToDownload = [
            ["url": "https://github.com/123seven/libmpv-android-video-build/releases/download/untagged-6e608b8debec5f0b1beb/default-arm64-v8a.jar", "sha256": "7931f910f40627d3d5cb2c7424935590ead30660c9b26cc340743667f3f30aa6", "destination": file("$buildDir/v1.2.4/default-arm64-v8a.jar")],
            ["url": "https://github.com/123seven/libmpv-android-video-build/releases/download/untagged-6e608b8debec5f0b1beb/default-armeabi-v7a.jar", "sha256": "bad425de4ebc34efc15eb74465efcf509353fd7c6a52db27bd8091e42b3b82f9", "destination": file("$buildDir/v1.2.4/default-armeabi-v7a.jar")],
            ["url": "https://github.com/123seven/libmpv-android-video-build/releases/download/untagged-6e608b8debec5f0b1beb/default-x86_64.jar", "sha256": "479af23318d49f13f7d4aa756214b86890aedfe819381d85ce31772c237a4bbc", "destination": file("$buildDir/v1.2.4/default-x86_64.jar")],
            ["url": "https://github.com/123seven/libmpv-android-video-build/releases/download/untagged-6e608b8debec5f0b1beb/default-x86.jar", "sha256": "70f3a4c95f7310231de08af3ca71b479d0adbdf5fa29981294e7568eb8d44f1f", "destination": file("$buildDir/v1.2.4/default-x86.jar")]
        ]

        filesToDownload.each { fileInfo ->
            def destFile = fileInfo.destination
            if (destFile.exists()) {
                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()

                if (calculatedSHA256 != fileInfo.sha256) {
                    destFile.delete()
                    println "SHA-256 mismatch. File deleted: ${destFile}"
                }

            }

            if (!destFile.exists()) {
                destFile.parentFile.mkdirs()
                println "Downloading file from: ${fileInfo.url}"
                destFile.withOutputStream { os ->
                    os << new URL(fileInfo.url).openStream()
                }

                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()
                if (calculatedSHA256 != fileInfo.sha256) {
                    throw new GradleException("SHA-256 verification failed for ${destFile}")
                }
            }

            copy {
                from destFile
                into outputDir
            }
        }
}

assemble.dependsOn(downloadDependencies)